name: Post Today’s TruckersMP Event

on:
  schedule:
    - cron: '30 18 * * *'  # Runs every day at 12:00 AM UTC
  workflow_dispatch:     # Allows manual trigger

jobs:
  post-event:
    runs-on: ubuntu-latest
    env:
      SHEET_ID1: ${{ secrets.SHEET_ID1 }}
      GOOGLE_APPLICATION_CREDENTIALS: service_account.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Write service account credentials
        run: echo '${{ secrets.GOOGLE_CREDS }}' > service_account.json

      - name: Run script
        run: python post_event.py
